stages:
  - frontend_build
  - backend_build
  - backend_deploy

variables:
  SSH_SERVER: 34.64.215.129
  SSH_PORT: 22
  SSH_USER: elice
  FRONT_TARGET_DIR: /front/build
  IMAGE_TAG: $CI_COMMIT_SHA

before_script:
  - 'which ssh-agent || (apk add --update openssh-client)'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $SSH_PORT $SSH_SERVER >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

frontend_build:
  stage: frontend_build
  script:
    - cd front
    - yarn install
    - yarn build
  artifacts:
    paths:
      - front/build/*

backend_build:
  stage: backend_build
  script:
    - cd back
    - docker buildx build --platform=linux/amd64 --load --tag daechanjo/wordy:$IMAGE_TAG .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push daechanjo/$IMAGE_TAG

backend_deploy:
  stage: backend_deploy
  script:
    - scp -P $SSH_PORT -r ./front/build/* $SSH_USER@$SSH_SERVER:$FRONT_TARGET_DIR
    - 'ssh -p $SSH_PORT $SSH_USER@$SSH_SERVER "docker pull daechanjo/wordy:$IMAGE_TAG"'
    - ssh -p $SSH_PORT $SSH_USER@$SSH_SERVER "sed -i 's|daechanjo/wordy:.*|daechanjo/$IMAGE_TAG|' docker-compose.yml"
    - 'ssh -p $SSH_PORT $SSH_USER@$SSH_SERVER "docker-compose down"'
    - 'ssh -p $SSH_PORT $SSH_USER@$SSH_SERVER "docker-compose up --build --detach"'
