stages:
  - autoPush

variables:
  BACK: back
  DAECHAN: feature/daechan

autoPush:
  stage: autoPush
  only:
    - $DAECHAN
  script:
    - git config user.name "[AI8/1반] 조대찬"
    - git config user.email "daechan476@gmail.com"
    - git checkout $BACK
    - git merge $DAECHAN
    - git push origin $BACK

# 배포까지 설정하지 않는 이상 굳이 사용해야할 필요가 있을까..?
# 특히 서버는 빌드가 필요없는데..? 프론트는 좋을듯
# 또 원격에 푸쉬하기 전에 커밋메시지 실수 등 바로잡을 기회가 사라짐
# 역으로 상위브랜치의 변경사항을 작업중인 브랜치로 자동 병합되게 하는것도 좀 위험함
# 무슨 코드가 올줄알고..?